### ISSUE TITLE
Bind parameters for SQL sentences to avoid SQL injection

### ISSUE THREAD

**Issue by SergioMD15** [jaykay12/KitabGhar#11]
The way the SQL sentences are implemented (concatenation of strings) is not safe and the system can be compromised if someone introduces some malicious input to achieve a SQL Injection attack. This should be easy to change and would improve a lot the security of your page.

**Comment by SergioMD15** [comment]
Sure

**Comment by jaykay12** [comment]
Closed by @SergioMD15 with PR #10
