### ISSUE TITLE
Add Icon to the Title Bar of the Portal

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/KitabGhar#16]
**Current Behavior:** 
![screenshot from 2018-10-03 00-56-26](https://user-images.githubusercontent.com/13948542/46378126-4ba22600-c6b8-11e8-9862-6f11237cab70.png)

**Required Behavior:**
Convert the image present at `projectImages/projectLogo.jpg` into .ico file & add it as the favicon icon to the portal.

**Important Info:**
Need to include the icon only in JSP File `HeaderTop.jsp`

**Comment by harleo** [comment]
I'm taking this.

**Comment by harleo** [comment]
Hey, apparently I need push access for the dev branch to add the favicon.
Do you want me to put it in the ProjectImages folder and link the HeaderTop.js to it?

**Comment by jaykay12** [comment]
Closed by #20 & #21 
Thanks @izambl & @harleo for your valuable contributions.

Happy Hacking :octocat:
