### ISSUE TITLE
Favicon icon on tabs shows white background

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/KitabGhar#28]
**Current Behavior:**
The favicon icon on the browser tab has a white background, which couldn't be removed even after using a transparent png file at `KitabGhar/ProjectImages/projectlogo.png`

![screenshot from 2018-10-17 00-21-30](https://user-images.githubusercontent.com/13948542/47040379-bc127200-d1a3-11e8-86a9-e79c9d078ac7.png)

**Required Behavior:**
The favicon should be transparent in nature.

Both Original jpg & Transparent png files are present at `KitabGhar/ProjectImages/`. Use either of them to generate .ico file which resolves the issue.

**Comment by skylerwlewis** [comment]
Maybe I am seeing something wrong, but this is already fixed for me. Tested in the latest versions of Chrome, Safari, & Firefox for Mac.

**Comment by satyajiit** [comment]
> **Current Behavior:**
> The favicon icon on the browser tab has a white background, which couldn't be removed even after using a transparent png file at `KitabGhar/ProjectImages/projectlogo.png`
> 
> ![screenshot from 2018-10-17 00-21-30](https://user-images.githubusercontent.com/13948542/47040379-bc127200-d1a3-11e8-86a9-e79c9d078ac7.png)
> 
> **Required Behavior:**
> The favicon should be transparent in nature.
> 
> Both Original jpg & Transparent png files are present at `KitabGhar/ProjectImages/`. Use either of them to generate .ico file which resolves the issue.

Working fine...You may just need to clear your browser (Perhaps Google Chrome ) cache memory and hit refresh.

**Comment by jaykay12** [comment]
Yeah Thanks @satyajiit @skylerwlewis for bringing into notice.
