### ISSUE TITLE
Redesign Admin Panel Using Bootstrap

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/KitabGhar#3]
These JSP Pages Require Changes:
 - AdminHandle.jsp
 - AdminRemoveBooks.jsp
 - AdminRemoveUser.jsp
 - AdminShowLibrary.jsp
 - AdminShowUserDetails.jsp
 - AdminShowUsers.jsp

**Comment by SergioMD15** [comment]
Hi, I'd like to work in this issue

**Comment by jaykay12** [comment]
Yes. Sure @SergioMD15  you can go ahead with this one.

**Comment by miguelesquirol** [comment]
This sounds right up my Alley

**Comment by jaykay12** [comment]
Resolved by @SergioMD15 with PR #10
